apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-config
  namespace: banking
data:
  DB_HOST: "dev-mysql-db.c8fi060w4183.us-east-1.rds.amazonaws.com"  
  DB_PORT: "3306"
  DB_NAME: "pod13fintech_db"
  REACT_APP_API_URL: "https://bankapi.pod13fintech.online"