apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-frontend-deployment
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-frontend-deployment
  template:
    metadata:
      labels:
        app: bank-frontend-deployment
    spec:
      containers:
      - name: bank-frontend-container
        image: 547268988762.dkr.ecr.us-east-1.amazonaws.com/bank-frontend:4
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: bank-config
              key: REACT_APP_API_URL
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 120